# Function: ret_globals
# Function: change_glob
# Function: get_module_obj
# Function: spec_type_mod
# Function: get_type_mod
# Function: is_module_obj
# Function: inspect_signature
# Function: get_parameter_defaults
# Function: call_functions_hard
# Function: convert_layout_to_components
# Function: get_dir
